### ISSUE TITLE
Remove 'static lifetime bound

### ISSUE THREAD

**Issue by jrmuizel** [TeXitoi/par-map#2]
Rayon doesn't seem to require 'static lifetime bound for it's parallel iterators. Is it possible to remove that requirement for par-map?

**Comment by TeXitoi** [comment]
I can't find any solution to remove the 'static bound without changing the interface. I think that's impossible.

**Comment by TeXitoi** [comment]
removing the 'static bound need a scoped_thread like scope, and thus is visible to the user interface. I can't find any way to remove this bound without added complexity at the user side, thus I close this issue.

If you have an idea, please reopen this issue and give it to me, I'd love to remove this bound.
